services:
  docs:
    image: titulos_2024_local_docs
    container_name: titulos_2024_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./titulos_2024:/app/titulos_2024:z
    ports:
      - '9000:9000'
    command: /start-docs
